version: '2'

services:

  ### CONTAINERS COMPARTILHADOS ENTRE OS AMBIENTES DE TESTE ###
  smtp:
    image: processoeletronico/vagrant_super4_mailcatcher:${ENVIRONMENT_VERSION}
    ports:
      - "1080:1080"

  org1-memcached:
    image: processoeletronico/vagrant_super4_memcached:${ENVIRONMENT_VERSION}
    ports:
      - "11211"

  org2-memcached:
    image: processoeletronico/vagrant_super4_memcached:${ENVIRONMENT_VERSION}
    ports:
      - "11211"

  proxy:
    image: diouxx/apache-proxy
    ports:
      - "8000:8000"
    volumes:
      - ./assets/proxy/:/opt/proxy-conf
    links:
      - org1-http:org1-http
      - org2-http:org2-http

  selenium:
    image: selenium/standalone-chrome-debug
    links:
      - proxy:org1-http
      - proxy:org2-http
    ports:
      - "4444:4444"
      - "5900:5900"
    volumes:
      - /dev/shm:/dev/shm
      - ./assets/arquivos/test_files_index.txt:/test_files_index.txt
      - /tmp:/tmp

  php-test-functional:
    image: processoeletronico/vagrant_super4_httpd:${ENVIRONMENT_VERSION}
    depends_on:
      - org1-database
      - org2-database
      - selenium
    volumes:
      - ${SEI_PATH}/sei:/opt/sei
      - ${SEI_PATH}/sip:/opt/sip
      - ${SEI_PATH}/infra:/opt/infra
      - ./assets/config:/opt/sei/config/mod-pen
      - .:/tests
      - /tmp:/tmp
    environment:
      - XDEBUG_CONFIG=client_host=host.docker.internal client_port=9003 start_with_request=0
      - XDEBUG_SESSION=default
      - XDEBUG_MODE=debug
      - CONTEXTO_ORGAO_A_DB_SEI_DSN=${CONTEXTO_ORGAO_A_DB_SEI_DSN}
      - CONTEXTO_ORGAO_B_DB_SEI_DSN=${CONTEXTO_ORGAO_B_DB_SEI_DSN}
      - SEI_DATABASE_USER=${SEI_DATABASE_USER}
      - SEI_DATABASE_PASSWORD=${SEI_DATABASE_PASSWORD}
      - ORG1_CERTIFICADO=${ORG1_CERTIFICADO}
      - ORG1_CERTIFICADO_SENHA=${ORG1_CERTIFICADO_SENHA}
      - ORG2_CERTIFICADO=${ORG2_CERTIFICADO}
      - ORG2_CERTIFICADO_SENHA=${ORG2_CERTIFICADO_SENHA}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    links:
      - org1-database:${ORG1_DATABASE_HOST}
      - org2-database:${ORG2_DATABASE_HOST}
      - selenium:selenium
    command: "true"

  php-test-unit:
    image: processoeletronico/vagrant_super4_httpd:${ENVIRONMENT_VERSION}
    volumes:
      - ${SEI_PATH}/sei:/opt/sei
      - ${SEI_PATH}/sip:/opt/sip
      - ${SEI_PATH}/infra:/opt/infra
      - ./assets/config:/opt/sei/config/mod-pen
      - ./assets/config/ConfiguracaoSEI.php:/opt/sei/config/ConfiguracaoSEI.php:ro
      - ./assets/config/ConfiguracaoSip.php:/opt/sip/config/ConfiguracaoSip.php:ro
      - ../unitario:/tests
      - ../../src:/opt/sei/web/modulos/pen
    environment:
      - XDEBUG_CONFIG=client_host=host.docker.internal client_port=9003 start_with_request=0
      - XDEBUG_SESSION=default
      - XDEBUG_MODE=debug
      - CONTEXTO_ORGAO_A_DB_SEI_DSN=${CONTEXTO_ORGAO_A_DB_SEI_DSN}
      - CONTEXTO_ORGAO_B_DB_SEI_DSN=${CONTEXTO_ORGAO_B_DB_SEI_DSN}
      - SEI_DATABASE_USER=${SEI_DATABASE_USER}
      - SEI_DATABASE_PASSWORD=${SEI_DATABASE_PASSWORD}
      - ORG1_CERTIFICADO=${ORG1_CERTIFICADO}
      - ORG1_CERTIFICADO_SENHA=${ORG1_CERTIFICADO_SENHA}
      - ORG2_CERTIFICADO=${ORG2_CERTIFICADO}
      - ORG2_CERTIFICADO_SENHA=${ORG2_CERTIFICADO_SENHA}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: "true"

  ### CONTAINERS DO AMBIENTE DO ÓRGÃO 1 ###

  org1-database:
    image: ${ORG1_DATABASE_IMAGE}:${ENVIRONMENT_VERSION}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssword
    ports:
      - "${ORG1_DATABASE_HOST_PORT}:${ORG1_DATABASE_GUEST_PORT}"

  org1-http:
    image: processoeletronico/vagrant_super4_httpd:${ENVIRONMENT_VERSION}
    restart: always
    depends_on:
      - org1-database
    volumes:
      - ${SEI_PATH}/sei:/opt/sei
      - ${SEI_PATH}/sip:/opt/sip
      - ${SEI_PATH}/infra:/opt/infra
      - ./assets/cron.d:/etc/cron.d
      - ./assets/config:/opt/sei/config/mod-pen
      - ./assets/config/ConfiguracaoSEI.php:/opt/sei/config/ConfiguracaoSEI.php:ro
      - ./assets/config/ConfiguracaoSip.php:/opt/sip/config/ConfiguracaoSip.php:ro
      - ../../src/scripts:/opt/sei/scripts/mod-pen
      - ../../src/scripts:/opt/sip/scripts/mod-pen
      - ../../src/bin:/opt/sei/bin/mod-pen
      - ../../src:/opt/sei/web/modulos/pen
    environment:
      - LANG=pt_BR.ISO-8859-1
      - HOST_URL=http://${ORG1_HOSTNAME}:${ORG1_PORT}
      - CERTIFICADO=${ORG1_CERTIFICADO}
      - CERTIFICADO_SENHA=${ORG1_CERTIFICADO_SENHA}
      - XDEBUG_CONFIG=client_host=host.docker.internal client_port=9003 start_with_request=0
      - XDEBUG_SESSION=default
      - XDEBUG_MODE=debug
      - APP_SIP_CHAVE_ACESSO=${ORG1_APP_SIP_CHAVE_ACESSO}
      - APP_SEI_CHAVE_ACESSO=${ORG1_APP_SEI_CHAVE_ACESSO}
      - DATABASE_TYPE=${ORG1_DATABASE_TYPE}
      - DATABASE_HOST=${ORG1_DATABASE_HOST}
      - DATABASE_PORT=${ORG1_DATABASE_GUEST_PORT}
      - CONTEXTO_ORGAO_A_DB_SEI_DSN=${CONTEXTO_ORGAO_A_DB_SEI_DSN}

      - SEI_CHAVE_ACESSO=${ORG1_APP_SEI_CHAVE_ACESSO}
      - SEI_DATABASE_NAME=${SEI_DATABASE_NAME}
      - SEI_DATABASE_USER=${SEI_DATABASE_USER}
      - SEI_DATABASE_PASSWORD=${SEI_DATABASE_PASSWORD}

      - SIP_CHAVE_ACESSO=${ORG1_APP_SIP_CHAVE_ACESSO}
      - SIP_DATABASE_NAME=${SIP_DATABASE_NAME}
      - SIP_DATABASE_USER=${SIP_DATABASE_USER}
      - SIP_DATABASE_PASSWORD=${SIP_DATABASE_PASSWORD}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    links:
      - org1-memcached:memcached
      - smtp:smtp
      - org1-database:${ORG1_DATABASE_HOST}

  ### CONTAINERS DO AMBIENTE DO ÓRGÃO 2 ###

  org2-database:
    image: ${ORG2_DATABASE_IMAGE}:${ENVIRONMENT_VERSION}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssword
    ports:
      - "${ORG2_DATABASE_HOST_PORT}:${ORG2_DATABASE_GUEST_PORT}"

  org2-http:
    image: processoeletronico/vagrant_super4_httpd:${ENVIRONMENT_VERSION}
    restart: always
    depends_on:
      - org2-database
    volumes:
      - ${SEI_PATH}/sei:/opt/sei
      - ${SEI_PATH}/sip:/opt/sip
      - ${SEI_PATH}/infra:/opt/infra
      - ./assets/cron.d:/etc/cron.d
      - ./assets/config:/opt/sei/config/mod-pen
      - ../../src/scripts:/opt/sei/scripts/mod-pen
      - ../../src/scripts:/opt/sip/scripts/mod-pen
      - ../../src/bin:/opt/sei/bin/mod-pen
      - ../../src:/opt/sei/web/modulos/pen
      - ./assets/config/ConfiguracaoSEI.php:/opt/sei/config/ConfiguracaoSEI.php:ro
      - ./assets/config/ConfiguracaoSip.php:/opt/sip/config/ConfiguracaoSip.php:ro
    environment:
      - LANG=pt_BR.ISO-8859-1
      - HOST_URL=http://${ORG2_HOSTNAME}:${ORG2_PORT}
      - CERTIFICADO=${ORG2_CERTIFICADO}
      - CERTIFICADO_SENHA=${ORG2_CERTIFICADO_SENHA}
      - XDEBUG_CONFIG=client_host=host.docker.internal client_port=9003 start_with_request=0
      - XDEBUG_SESSION=default
      - XDEBUG_MODE=debug
      - APP_SIP_CHAVE_ACESSO=${ORG2_APP_SIP_CHAVE_ACESSO}
      - APP_SEI_CHAVE_ACESSO=${ORG2_APP_SEI_CHAVE_ACESSO}
      - DATABASE_TYPE=${ORG2_DATABASE_TYPE}
      - DATABASE_HOST=${ORG2_DATABASE_HOST}
      - DATABASE_PORT=${ORG2_DATABASE_GUEST_PORT}
      - CONTEXTO_ORGAO_B_DB_SEI_DSN=${CONTEXTO_ORGAO_B_DB_SEI_DSN}

      - SEI_CHAVE_ACESSO=${ORG2_APP_SEI_CHAVE_ACESSO}
      - SEI_DATABASE_NAME=${SEI_DATABASE_NAME}
      - SEI_DATABASE_USER=${SEI_DATABASE_USER}
      - SEI_DATABASE_PASSWORD=${SEI_DATABASE_PASSWORD}

      - SIP_CHAVE_ACESSO=${ORG2_APP_SIP_CHAVE_ACESSO}
      - SIP_DATABASE_NAME=${SIP_DATABASE_NAME}
      - SIP_DATABASE_USER=${SIP_DATABASE_USER}
      - SIP_DATABASE_PASSWORD=${SIP_DATABASE_PASSWORD}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    links:
      - org2-memcached:memcached
      - smtp:smtp
      - org2-database:${ORG2_DATABASE_HOST}
